name: Autoclose dependabot alerts
on:
  workflow_dispatch:
    inputs:
    branches: [ master ]
jobs:
  close:
    if: ${{ github.actor == 'dependabot' }}
    runs-on: ubuntu-latest
  steps:
    - name: close pull
      uses: peter-evans/close-pull@v1
      with:
        delete-branch: true
