name: Autoclose dependabot alerts

on:
  workflow_dispatch:
    

jobs:
  close:
    if: ${{ github.actor == 'dependabot' }}
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: close pull
      uses: peter-evans/close-pull@v1
      with:
        comment: Auto-closing pull request
        delete-branch: true
