name: Autoclose dependabot alerts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to execute tests on (dev, test, stage)'
        required: true
        default: 'test'

jobs:
  close:
    if: ${{ github.actor == 'dependabot' }}
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: close pull
      uses: peter-evans/close-pull@v1
      with:
        delete-branch: true
